"use client";

import { useEffect, useState } from "react";

type Lang = "zh" | "en";
type Screen = "landing" | "sources" | "processing" | "book";
type Chapter = "past" | "self" | "now" | "future" | "plan";

const copy = {
  zh: {
    how: "它如何工作", eyebrow: "一本属于你的人生之书", headline1: "读懂你走过的路，", headline2: "看见你正在成为谁。",
    sub: "InnerOS 将散落的聊天、日记与生活片段，整理成一条有证据的人生主线——帮助你理解自己，也看清下一章。",
    create: "生成我的人生之书", demo: "使用演示人生", trust: "无需注册 · 演示资料不会被保存", noDefine: "不替你定义人生。",
    promises: [["整理经历","从碎片中找到主线"],["看见模式","每个洞察都有证据"],["写下下一章","把理解变成行动"]],
    disclaimer: "InnerOS 不是心理诊断或决策替代工具。它帮助你整理经历、发现模式，并形成自己的答案。",
    sourcesTitle: "先聊聊，现在的你。", sourcesSub: "说说最近让你反复想到的一件事，或者直接导入一段生活记录。InnerOS 会陪你从一个片段开始，慢慢找到主线。",
    demoTitle: "林晓的转折之年", demoDesc: "一位 29 岁的产品设计师，在晋升受挫后重新思考工作、关系和创造。",
    range: "2025年10月—2026年9月", fragments: "18 段生活片段", selected: "演示故事", useStory: "直接体验林晓的人生", guide: "你不需要一次讲完", guideSub: "想到哪里，就从哪里开始。", begin: "发送",
    sources: ["微信","ChatGPT","日记","备忘录","日历"], coming: "即将支持", private: "演示资料仅用于当前体验，不会上传或保存你的私人记录。",
    processingTitle: "正在读懂这段人生…", processingSub: "我们先整理事实，再尝试理解。每一个判断都将保留证据。",
    steps: ["整理 18 个关键事件","识别 3 个人生阶段","连接人物与主题","寻找重复模式","起草人生的下一章"], done: "完成", fallback: "正在使用稳定的演示结果",
    lifeBook: "我的人生之书", bookName: "林晓的人生之书", edition: "第一版 · 2026年9月", saved: "已保存",
    nav: ["我从哪里来","我是谁","我在哪里","我要去哪里"], ownership: "你的书，由你定义", ownershipSub: "所有洞察都可以查看、纠正或隐藏。",
    chapters: ["CHAPTER ONE","CHAPTER TWO","CHAPTER THREE","CHAPTER FOUR"],
    pastTitle: "我从哪里来", pastLede: "你过去一年不是在“不断换方向”，而是在逐渐从外部认可，走向一种更忠于自己的创造。", theme: "贯穿主题", themeText: "从证明自己，到表达自己", evidence7: "7 条证据",
    stages: [
      ["2025.10 — 2026.01","第一阶段","加速奔跑","你接下更多项目，把忙碌当成进步的证明。来自同事的肯定让你安心，但独处时，你开始问：“这真的是我想要的吗？”"],
      ["2026.02 — 2026.05","转折点","第一次停下来","一次错过的晋升让你失落，却也打开了新的问题：如果不再用职位衡量自己，你真正想创造什么？"],
      ["2026.06 — 至今","正在发生","寻找自己的语言","你开始写作、做独立项目，也重新连接那些让你感到真实的人。方向还不完整，但判断标准已经改变。"]
    ], quote: "“你不是迷路了，你只是不再愿意沿着旧地图前进。”", next: "下一章：我是谁",
    selfTitle: "我是谁", selfLede: "这些不是关于你的最终答案，而是目前最值得与你核对的三种模式。",
    insights: [
      ["重复模式","不确定 → 寻找更多认可 → 短暂安心","当方向不明确时，你常用更多工作和外部反馈来恢复控制感。","高可信","6 个事件"],
      ["优势与代价","你很擅长理解别人，却容易延后自己的需要","共情让你成为可靠的伙伴，也让你在冲突中更常先解释对方。","中高可信","5 个事件"],
      ["正在改变","成就不再是你唯一的衡量标准","过去三个月，你描述满足感时更多提到创造、连接与自主。","中高可信","7 个事件"]
    ], viewEvidence: "查看证据", fits: "符合我", notFits: "不符合", addContext: "需要补充", feedbackThanks: "已记录。你的理解会成为这本书的一部分。",
    nowTitle: "我在哪里", nowLede: "你正站在旧的成功标准与新的生活语言之间。现在最重要的，不是立刻选对方向，而是建立新的判断标准。",
    currentStage: "当前阶段", currentStageText: "重新定义成功", questions: "三个核心课题", questionList: ["怎样的工作值得投入我的创造力？","哪些关系让我更接近真实的自己？","如果不急着证明，我想怎样度过一天？"], energy: "精力流向", energyItems: [["独立创造","38%"],["工作责任","34%"],["重要关系","18%"],["恢复与独处","10%"]], tension: "尚未解决的张力", tensionText: "你想要自由，却仍然用旧有的成就标准判断自由是否“值得”。",
    futureTitle: "我要去哪里", futureLede: "下一章不是一个职业答案，而是一场为期三个月的实验：让创造从周末的例外，变成生活的固定部分。",
    nextChapter: "建议的下一章", nextTitle: "把自己的声音放回生活中心", protect: "想守护的价值", values: ["创造","自主","真诚的连接"], continue: "继续", continueText: "每周公开一份小作品", stop: "停止", stopText: "用忙碌证明自己的价值", try: "尝试", tryText: "和三位独立创作者交流真实工作状态", smallest: "本周最小的一步", smallestText: "周六上午留出 90 分钟，只推进那个你一直想做的个人项目。", makePlan: "把建议变成计划",
    planTitle: "把下一章变成一场实验", planLede: "这不是一份新的自我要求，而是一套帮助你收集真实反馈的轻量计划。", direction: "方向", directionText: "让创造成为稳定的生活组成，而不是忙完后的奖励。", goal: "未来 12 周", goalText: "完成并公开 6 个小作品，从真实反馈中判断下一步。", habits: "建议习惯", habitList: [["每周两次","45 分钟无评价创作"],["每周一次","公开一个过程或作品"],["每月一次","回到 InnerOS 更新人生之书"]], obstacle: "历史模式提醒", obstacleText: "你可能会在不确定时继续收集信息。发现自己连续研究两天时，先完成一个可见的小版本。", fallbackLabel: "低能量替代方案", fallbackText: "如果无法创作 45 分钟，只写下一个想法并为它命名。", backBook: "返回人生之书",
    evidenceTitle: "这条洞察从哪里来", evidenceInsight: "不确定 → 寻找更多认可 → 短暂安心", evidenceItems: [
      ["2025.11 · 微信","“最近有点不知道自己做的东西有没有价值，所以又接了两个项目。忙起来至少不会多想。”","你把忙碌描述成缓解不确定感的方式。"],
      ["2026.02 · 日记","“没升职的第一反应，是不是应该再证明一下自己。”","受挫后，你首先想到增加付出，而不是重新审视目标。"],
      ["2026.06 · ChatGPT","“我查了很多转行路线，但越看越不知道自己真正想做什么。”","更多信息没有带来持久清晰，反而延后了尝试。"]
    ], why: "AI 的理解", alternative: "另一种可能", alternativeText: "这些行为也可能来自你对工作的责任感，而不仅是对认可的需要。你拥有最终解释权。", close: "关闭"
  },
  en: {
    how: "How it works", eyebrow: "A life book that belongs to you", headline1: "Understand the life you’ve lived—", headline2: "and the person you’re becoming.",
    sub: "InnerOS turns scattered chats, journals, and life moments into an evidence-backed story—so you can understand yourself and see what comes next.",
    create: "Create My Life Book", demo: "Try a Demo Story", trust: "No sign-up · Demo data is never saved", noDefine: "Not here to define your life.",
    promises: [["Gather your story","Find the thread in the fragments"],["See your patterns","Every insight carries evidence"],["Write the next chapter","Turn understanding into action"]],
    disclaimer: "InnerOS is not a diagnostic or decision-making tool. It helps you organize experiences, notice patterns, and form your own answers.",
    sourcesTitle: "Let's begin with who you are today.", sourcesSub: "Share something that's been on your mind, or bring in a piece of your life. InnerOS will start with one fragment and help you find the thread.",
    demoTitle: "Lin's year of transition", demoDesc: "A 29-year-old product designer rethinking work, relationships, and creativity after a missed promotion.", range: "Oct 2025—Sep 2026", fragments: "18 life fragments", selected: "Demo story", useStory: "Explore Lin's story", guide: "You don't need to tell it all at once", guideSub: "Begin wherever your mind keeps returning.", begin: "Send",
    sources: ["WeChat","ChatGPT","Journal","Notes","Calendar"], coming: "Coming soon", private: "Demo data is used only for this experience. Your private records are not uploaded or saved.",
    processingTitle: "Reading this life…", processingSub: "We organize facts before we attempt interpretation. Every conclusion keeps its evidence.", steps: ["Organizing 18 key events","Finding 3 life stages","Connecting people and themes","Looking for recurring patterns","Drafting the next chapter"], done: "Done", fallback: "Using a stable demo result",
    lifeBook: "My Life Book", bookName: "Lin's Life Book", edition: "First edition · September 2026", saved: "Saved", nav: ["Where I came from","Who I am","Where I am","Where I'm going"], ownership: "Your book, your meaning", ownershipSub: "Every insight can be examined, corrected, or hidden.", chapters: ["CHAPTER ONE","CHAPTER TWO","CHAPTER THREE","CHAPTER FOUR"],
    pastTitle: "Where I came from", pastLede: "The last year wasn't about constantly changing direction. It was a gradual move from external approval toward a more honest kind of creation.", theme: "Through-line", themeText: "From proving yourself to expressing yourself", evidence7: "7 sources",
    stages: [["Oct 2025 — Jan 2026","First stage","Running faster","You took on more projects and treated busyness as proof of progress. Colleagues’ praise felt reassuring, but alone you began asking: is this what I want?"],["Feb — May 2026","Turning point","The first pause","Missing a promotion hurt, but opened a new question: if title no longer defines you, what do you actually want to create?"],["Jun 2026 — Now","In progress","Finding your own language","You began writing, building side projects, and reconnecting with people who make you feel real. The direction is incomplete, but the standard has changed."]], quote: "“You are not lost. You are simply no longer willing to follow the old map.”", next: "Next: Who I am",
    selfTitle: "Who I am", selfLede: "These are not final answers about you. They are three patterns most worth checking together.", insights: [["RECURRING PATTERN","Uncertainty → more approval → brief relief","When direction is unclear, you often use more work and outside feedback to regain control.","High confidence","6 events"],["STRENGTH & COST","You understand others well, but postpone your own needs","Empathy makes you reliable, while also leading you to explain others first during conflict.","Medium-high","5 events"],["WHAT'S CHANGING","Achievement is no longer your only measure","In the past three months, you described fulfillment more through creativity, connection, and autonomy.","Medium-high","7 events"]], viewEvidence: "View evidence", fits: "Feels true", notFits: "Not me", addContext: "Add context", feedbackThanks: "Noted. Your understanding becomes part of this book.",
    nowTitle: "Where I am", nowLede: "You are standing between an old definition of success and a new language for living. The work now isn't to choose perfectly, but to build a better compass.", currentStage: "Current stage", currentStageText: "Redefining success", questions: "Three live questions", questionList: ["What work deserves my creative energy?","Which relationships bring me closer to myself?","Without needing to prove anything, how would I spend a day?"], energy: "Where energy goes", energyItems: [["Independent creation","38%"],["Work obligations","34%"],["Close relationships","18%"],["Rest & solitude","10%"]], tension: "Unresolved tension", tensionText: "You want freedom, yet still judge whether that freedom is ‘worth it’ by old achievement standards.",
    futureTitle: "Where I'm going", futureLede: "The next chapter is not a career answer. It is a three-month experiment: make creation a regular part of life instead of a weekend exception.", nextChapter: "Suggested next chapter", nextTitle: "Put your own voice back at the center", protect: "Values to protect", values: ["Creativity","Autonomy","Honest connection"], continue: "CONTINUE", continueText: "Share one small piece each week", stop: "STOP", stopText: "Using busyness to prove your worth", try: "TRY", tryText: "Talk with three independent creators about daily reality", smallest: "The smallest step this week", smallestText: "Reserve 90 minutes Saturday morning for the personal project you keep postponing.", makePlan: "Turn this into a plan",
    planTitle: "Turn the next chapter into an experiment", planLede: "Not another demand on yourself—a light structure for gathering honest feedback.", direction: "Direction", directionText: "Make creation a stable part of life, not a reward after the work is done.", goal: "The next 12 weeks", goalText: "Complete and share 6 small pieces, then use real feedback to choose what comes next.", habits: "Suggested habits", habitList: [["Twice a week","45 minutes of judgment-free making"],["Once a week","Share a process or finished piece"],["Once a month","Return to InnerOS and update your book"]], obstacle: "Historical pattern to watch", obstacleText: "You may keep researching when uncertain. When you notice two days of continuous research, make one visible small version first.", fallbackLabel: "Low-energy alternative", fallbackText: "If 45 minutes is too much, write down one idea and give it a name.", backBook: "Back to my life book",
    evidenceTitle: "Where this insight came from", evidenceInsight: "Uncertainty → more approval → brief relief", evidenceItems: [["Nov 2025 · WeChat","“I’m not sure my work has value, so I took on two more projects. At least staying busy keeps me from overthinking.”","Busyness is described as a way to reduce uncertainty."],["Feb 2026 · Journal","“My first response to missing the promotion was: maybe I need to prove myself again.”","After a setback, the first impulse was more effort rather than reconsidering the goal."],["Jun 2026 · ChatGPT","“I researched so many career paths, but the more I read, the less I know what I really want.”","More information did not create lasting clarity and delayed experimentation."]], why: "AI's reading", alternative: "Another possibility", alternativeText: "These actions may also reflect responsibility toward your work, not only a need for approval. You hold the final interpretation.", close: "Close"
  }
} as const;

export default function Home() {
  const [lang, setLang] = useState<Lang>("zh"); const [screen, setScreen] = useState<Screen>("landing"); const [chapter, setChapter] = useState<Chapter>("past");
  const [progress, setProgress] = useState(0); const [evidence, setEvidence] = useState(false); const [feedback, setFeedback] = useState<string | null>(null);
  const t = copy[lang];
  useEffect(() => { if (screen !== "processing") return; setProgress(0); const timer = setInterval(() => setProgress(p => { if (p >= 5) { clearInterval(timer); setTimeout(() => { setChapter("past"); setScreen("book"); }, 450); return p; } return p + 1; }), 520); return () => clearInterval(timer); }, [screen]);
  const toggleLang = () => setLang(lang === "zh" ? "en" : "zh");

  if (screen === "landing") return <Landing t={t} toggleLang={toggleLang} start={() => setScreen("sources")} />;
  if (screen === "sources") return <Sources t={t} toggleLang={toggleLang} back={() => setScreen("landing")} generate={() => setScreen("processing")} />;
  if (screen === "processing") return <Processing t={t} progress={progress} />;
  return <Book t={t} chapter={chapter} setChapter={setChapter} toggleLang={toggleLang} home={() => setScreen("landing")} evidence={() => setEvidence(true)} feedback={feedback} setFeedback={setFeedback} drawer={evidence} closeDrawer={() => setEvidence(false)} />;
}

function Landing({t,toggleLang,start}:{t:typeof copy["zh"]|typeof copy["en"],toggleLang:()=>void,start:()=>void}) { return <main className="landing"><nav className="topbar"><div className="brand">Inner<span>OS</span></div><div><button className="text-button">{t.how}</button><button className="lang" onClick={toggleLang}>中 / EN</button></div></nav><section className="hero"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.headline1}<br/><em>{t.headline2}</em></h1><p className="subtitle">{t.sub}</p><div className="cta-row"><button className="primary" onClick={start}>{t.create} <span>→</span></button><button className="secondary" onClick={start}>{t.demo}</button></div><p className="trust">○ {t.trust}</p></div><div className="book-preview life-poster"><div className="poster-label">LIFE IN PROGRESS<br/><b>2025—2026</b></div><div className="poster-path"><i></i><i></i><i></i><i></i></div><div className="poster-circle c1"><span>01</span></div><div className="poster-circle c2"><span>02</span></div><div className="poster-circle c3"><span>03</span><b className="tiny-person">●</b></div><div className="poster-note">{t.theme}<br/><b>{t.themeText}</b></div></div></section><section className="promise"><p>{t.noDefine}</p>{t.promises.map((p,i)=><div key={p[0]}><span>0{i+1}</span><b>{p[0]}</b><small>{p[1]}</small></div>)}</section><footer className="disclaimer">{t.disclaimer}</footer></main> }

function Sources({t,toggleLang,back,generate}:{t:any,toggleLang:()=>void,back:()=>void,generate:()=>void}) { const isZh=t.begin==="发送"; return <main className="sources-screen input-screen"><header className="app-header"><button className="brand" onClick={back}>Inner<span>OS</span></button><button className="lang" onClick={toggleLang}>中 / EN</button></header><section className="input-wrap"><div className="input-intro"><p className="eyebrow">A CONVERSATION · 01</p><h1>{t.sourcesTitle}</h1><p>{t.sourcesSub}</p></div><div className="ai-thread"><div className="ai-message"><span>IO</span><p>{isZh?"最近，什么事情最常出现在你的脑海里？它不一定是最大的问题，只要是你想从这里开始的地方。":"What has been returning to your mind lately? It doesn't need to be your biggest problem—just the place you want to begin."}</p></div><div className="composer"><textarea aria-label={isZh?"告诉 InnerOS":"Tell InnerOS"} placeholder={isZh?"可以是一段困惑、最近发生的事，或一个你正在做的决定…":"A question, a recent moment, or a decision you're facing…"}></textarea><div className="import-row"><button title={isZh?"添加链接":"Add link"}>↗ <span>{isZh?"链接":"Link"}</span></button><button title={isZh?"添加照片":"Add photos"}>▧ <span>{isZh?"照片":"Photos"}</span></button><button title={isZh?"导入 AI 记录":"Import AI history"}>✦ <span>{isZh?"AI 记录":"AI history"}</span></button><button title={isZh?"上传文件":"Upload file"}>＋ <span>{isZh?"文件":"File"}</span></button><button className="send-button" onClick={generate}>↑</button></div></div><p className="input-hint">{t.guide} · {t.guideSub}</p></div><div className="demo-divider"><span>{isZh?"或者先看看一个完整例子":"OR EXPLORE A COMPLETE EXAMPLE"}</span></div><article className="demo-strip"><div className="demo-orb"><b>林</b><i></i></div><div><small>{t.selected} · {t.range}</small><h2>{t.demoTitle}</h2><p>{t.demoDesc}</p></div><button onClick={generate}>{t.useStory} →</button></article><p className="source-privacy">○ {t.private}</p></section></main> }

function Processing({t,progress}:{t:any,progress:number}) { const pct=Math.min(100,progress*20); return <main className="processing-screen"><div className="processing-inner"><div className="orbit"><div className="orbit-ring"></div><div className="orbit-book">IO</div></div><p className="eyebrow">INNEROS · READING</p><h1>{t.processingTitle}</h1><p>{t.processingSub}</p><div className="progress-track"><i style={{width:`${pct}%`}}></i></div><div className="processing-steps">{t.steps.map((s:string,i:number)=><div className={i<progress?"complete":i===progress?"active":""} key={s}><span>{i<progress?"✓":String(i+1).padStart(2,"0")}</span><b>{s}</b><small>{i<progress?t.done:i===progress?"…":""}</small></div>)}</div><small className="fallback">◇ {t.fallback}</small></div></main> }

function Book({t,chapter,setChapter,toggleLang,home,evidence,feedback,setFeedback,drawer,closeDrawer}:{t:any,chapter:Chapter,setChapter:(c:Chapter)=>void,toggleLang:()=>void,home:()=>void,evidence:()=>void,feedback:string|null,setFeedback:(s:string)=>void,drawer:boolean,closeDrawer:()=>void}) { const chapters:Chapter[]=["past","self","now","future"]; const current=chapter==="plan"?3:chapters.indexOf(chapter); return <main className="book-shell"><header className="app-header"><button className="brand" onClick={home}>Inner<span>OS</span></button><div className="header-actions"><span className="saved">● {t.saved}</span><button className="lang" onClick={toggleLang}>中 / EN</button><button className="avatar">林</button></div></header><div className="book-layout"><aside className="book-nav"><p className="eyebrow">{t.lifeBook}</p><h1>{t.bookName}</h1><p className="edition">{t.edition}</p><nav>{chapters.map((c,i)=><button key={c} className={chapter===c||chapter==="plan"&&c==="future"?"active":""} onClick={()=>setChapter(c)}><span>0{i+1}</span> {t.nav[i]}</button>)}</nav><div className="privacy-note"><span>◇</span><p><b>{t.ownership}</b><br/>{t.ownershipSub}</p></div></aside><section className="chapter-page"><div className="chapter-kicker"><span>{chapter==="plan"?"ACTION PLAN":t.chapters[current]}</span><span>0{current+1} / 04</span></div>{chapter==="past"&&<Past t={t} evidence={evidence} next={()=>setChapter("self")}/>} {chapter==="self"&&<SelfChapter t={t} evidence={evidence} feedback={feedback} setFeedback={setFeedback}/>} {chapter==="now"&&<Now t={t}/>} {chapter==="future"&&<Future t={t} plan={()=>setChapter("plan")}/>} {chapter==="plan"&&<Plan t={t} back={()=>setChapter("future")}/>}</section></div>{drawer&&<EvidenceDrawer t={t} close={closeDrawer}/>}</main> }

function Past({t,evidence,next}:{t:any,evidence:()=>void,next:()=>void}) { return <><h2>{t.pastTitle}</h2><p className="chapter-lede">{t.pastLede}</p><div className="theme-row"><span>{t.theme}</span><strong>{t.themeText}</strong><button onClick={evidence}>{t.evidence7} ↗</button></div><div className="timeline">{t.stages.map((s:string[],i:number)=><article className={i===1?"turning":""} key={s[2]}><time>{s[0]}</time><div className="dot"></div><div><span className="phase">{s[1]}</span><h3>{s[2]}</h3><p>{s[3]}</p>{i===1?<button className="evidence-link" onClick={evidence}>{t.viewEvidence} →</button>:<div className="tags"><span>{i===0?"事业":"创造"}</span><span>{i===0?"自我价值":"成长"}</span></div>}</div></article>)}</div><div className="page-footer"><p>{t.quote}</p><button onClick={next}>{t.next} <span>→</span></button></div></> }

function SelfChapter({t,evidence,feedback,setFeedback}:{t:any,evidence:()=>void,feedback:string|null,setFeedback:(s:string)=>void}) { return <><h2>{t.selfTitle}</h2><p className="chapter-lede">{t.selfLede}</p><div className="insight-grid">{t.insights.map((item:string[],i:number)=><article className="insight-card" key={item[1]}><div className="insight-top"><span>{item[0]}</span><small>{item[3]} · {item[4]}</small></div><h3>{item[1]}</h3><p>{item[2]}</p><button className="evidence-link" onClick={evidence}>{t.viewEvidence} →</button><div className="feedback-row"><button className={feedback===`${i}-yes`?"chosen":""} onClick={()=>setFeedback(`${i}-yes`)}>✓ {t.fits}</button><button className={feedback===`${i}-no`?"chosen":""} onClick={()=>setFeedback(`${i}-no`)}>× {t.notFits}</button><button onClick={()=>setFeedback(`${i}-more`)}>＋ {t.addContext}</button></div>{feedback?.startsWith(`${i}-`)&&<small className="feedback-note">✓ {t.feedbackThanks}</small>}</article>)}</div></> }

function Now({t}:{t:any}) { return <><h2>{t.nowTitle}</h2><p className="chapter-lede">{t.nowLede}</p><div className="stage-banner"><span>{t.currentStage}</span><h3>{t.currentStageText}</h3><div className="stage-mark">BETWEEN<br/>CHAPTERS</div></div><div className="now-grid"><article><span className="section-label">{t.questions}</span><ol>{t.questionList.map((q:string)=><li key={q}>{q}</li>)}</ol></article><article><span className="section-label">{t.energy}</span><div className="energy-list">{t.energyItems.map((e:string[])=><div key={e[0]}><span>{e[0]}</span><i><b style={{width:e[1]}}></b></i><strong>{e[1]}</strong></div>)}</div></article></div><div className="tension-card"><span>↔</span><div><small>{t.tension}</small><p>{t.tensionText}</p></div></div></> }

function Future({t,plan}:{t:any,plan:()=>void}) { return <><h2>{t.futureTitle}</h2><p className="chapter-lede">{t.futureLede}</p><div className="next-chapter-card"><span className="section-label">{t.nextChapter}</span><h3>{t.nextTitle}</h3><div className="value-row"><small>{t.protect}</small>{t.values.map((v:string)=><b key={v}>{v}</b>)}</div></div><div className="three-actions"><article><span>↗</span><small>{t.continue}</small><p>{t.continueText}</p></article><article><span>—</span><small>{t.stop}</small><p>{t.stopText}</p></article><article><span>＋</span><small>{t.try}</small><p>{t.tryText}</p></article></div><div className="smallest-step"><div><small>{t.smallest}</small><p>{t.smallestText}</p></div><button className="primary" onClick={plan}>{t.makePlan} <span>→</span></button></div></> }

function Plan({t,back}:{t:any,back:()=>void}) { return <><button className="back-link" onClick={back}>← {t.backBook}</button><h2>{t.planTitle}</h2><p className="chapter-lede">{t.planLede}</p><div className="plan-summary"><article><small>{t.direction}</small><p>{t.directionText}</p></article><article><small>{t.goal}</small><p>{t.goalText}</p></article></div><span className="section-label">{t.habits}</span><div className="habit-list">{t.habitList.map((h:string[],i:number)=><div key={h[1]}><span>0{i+1}</span><b>{h[0]}</b><p>{h[1]}</p><i>○</i></div>)}</div><div className="plan-notes"><article><span>!</span><div><small>{t.obstacle}</small><p>{t.obstacleText}</p></div></article><article><span>↘</span><div><small>{t.fallbackLabel}</small><p>{t.fallbackText}</p></div></article></div></> }

function EvidenceDrawer({t,close}:{t:any,close:()=>void}) { return <div className="drawer-wrap" role="dialog" aria-modal="true"><button className="drawer-backdrop" aria-label={t.close} onClick={close}></button><aside className="drawer"><div className="drawer-head"><div><span className="eyebrow">EVIDENCE</span><h2>{t.evidenceTitle}</h2></div><button onClick={close}>×</button></div><h3>{t.evidenceInsight}</h3><div className="evidence-list">{t.evidenceItems.map((e:string[])=><article key={e[0]}><time>{e[0]}</time><blockquote>{e[1]}</blockquote><small>{t.why}</small><p>{e[2]}</p></article>)}</div><div className="alternative"><span>◇</span><div><b>{t.alternative}</b><p>{t.alternativeText}</p></div></div><button className="primary drawer-close" onClick={close}>{t.close}</button></aside></div> }
